### ISSUE TITLE
Create/amend utility functions to support detached inventories (or, generic inventory locations)

### ISSUE THREAD

**Issue by orwell96** [auouymous/node_io#1]
First of all, nice API concept. I'd like to incorporate it for the advtrains loading rails someday. (http://git.bananach.space/advtrains.git)

I noticed that your utility functions currently only handle node inventories. (You need to pass a node pos to them). Since wagons in my trains mod use detached inventories, it would be better if your utility functions could take an 'inventory location' (as specified in minetest's lua_api.txt) or something similar.

Remember, I am not talking about the node definition functions (node_io_get...), but the helper functions (node_io.get...). Whenever something calls the api functions on the loading node, it will delegate those calls to the wagon positioned there.

I can even imagine a machine that puts/takes stuff from a player's inventory using your API :)

**Comment by auouymous** [comment]
That lua_api.txt file doesn't explain what a detached inventory is, but it looks like an inventory in an entity. Is that correct?

It would be possible to handle entities but it would need an additional API for entities to implement (entity_io_*), and entity_io.* utility functions that call into entities.

Transfer nodes would also need to support entity_io. They currently have to get the node at a position and ask the API if that node supports node_io. If entity support was implicit, there could a node and multiple entities at the position and all transfer nodes would have to iterate over a list. A pipe is a transfer node and can take or put in any adjacent inventory. It can check on placement or on each tick for adjacent nodes that support node_io and adapt its model to indicate a connection. If player supports node_io and walks next to a pipe, the pipe model could change to indicate a connection and would start putting or taking from the player. So it would be best to separate the two APIs and let transfer nodes choose to support one or both APIs. A hopper could take from a chest above and put in a chest minecart below. Or take from a chest minecart above and put in a chest below.

I also don't think players should support entity_io. It would be easier for a node to directly access the player's inventory and put/take items. A node could easily check a specific player's inventory for a stack of cobble and if not found or not full, it could use node_io to take from an adjacent inventory and put in player's inventory. Imagine the hopper supports node_io and entity_io and a player walking on the track either gets their inventory sucked dry or filled up. Players are special entities and should be supported directly.

**Comment by orwell96** [comment]
No, you seem to have misunderstood me. I don't want you to create a API for entites.
Detached Inventories are inventories that are not assigned to specific nodes, or to a player.
Think of my situation as follows: There is a node, a detached inventory (so it's not saved in the node metadata, but somewhere else) and a tube that wants to take an item out of the node. The node implements the node_io_... callbacks for this and delegates the calls not to the node metadata inventory (minetest.get_meta(pos):get_inventory()) but to that certain detached inventory (minetest.get_detached_inventory("foo")). What I want to do now is using your "utility functions" node_io.* with that specific inventory, and not the node meta one.

**Comment by orwell96** [comment]
Example:
```
node_io.get_inventory_name = function(pos, inv_name, index)
	local inv = minetest.get_meta(pos):get_inventory()
	if not inv or index < 1 or index > inv:get_size(inv_name) then return "" end
	return inv:get_stack(inv_name, index):get_name()
end
```
should instead be something like this
```
node_io.get_inventory_name = function(pos, inv_name, index)
	local inv = minetest.get_meta(pos):get_inventory()
	if not inv or index < 1 or index > inv:get_size(inv_name) then return "" end
	return inv:get_stack(inv_name, index):get_name()
end
```

**Comment by orwell96** [comment]
Example:
```
node_io.get_inventory_name = function(pos, inv_name, index)
	local inv = minetest.get_meta(pos):get_inventory()
	if not inv or index < 1 or index > inv:get_size(inv_name) then return "" end
	return inv:get_stack(inv_name, index):get_name()
end
```
should instead be something like this
```
node_io.get_inventory_name = function(loc, inv_name, index)
	local inv = minetest.get_inventory(loc)
	if not inv or index < 1 or index > inv:get_size(inv_name) then return "" end
	return inv:get_stack(inv_name, index):get_name()
end
```

**Comment by auouymous** [comment]
What is the purpose of a node having a detached inventory?

Are you just asking for the implementation helper functions to support a position or an inventory location? I can easily have them check if the pos parameter is a string and call minetest.get_inventory(pos) to get the detached inventory. But I imagine most nodes using the helper functions have a standard inventory and directly passing pos would be easier and faster than converting to a "nodemeta:..." string.

**Comment by orwell96** [comment]
> Are you just asking for the implementation helper functions to support a position or an inventory location?

Exactly. And you are right, this is a rather special edge case. I won't force you into anything, but you could consider adding a further check.

**Comment by auouymous** [comment]
Support has been added - see https://github.com/auouymous/node_io/blob/master/API#L99

**Comment by orwell96** [comment]
Thx
